version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 4 --worker-class gthread --threads 2 --access-logfile - backend.wsgi:application"
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgresql://nasa_user:T3mp0@!2025_N4S4_A1rQu4l1ty@db:5432/nasa_tempo_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SECRET_KEY=vl*!l+17p8xg@^s8kd0cq5ug2ogylivy#93k=gi^#aw1p^_ys1
      - ALLOWED_HOSTS=localhost,127.0.0.1,.onrender.com,.render.com
      - CORS_ALLOWED_ORIGINS=https://your-frontend-domain.com,http://localhost:3000
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nasa_tempo_db
      - POSTGRES_USER=nasa_user
      - POSTGRES_PASSWORD=T3mp0@!2025_N4S4_A1rQu4l1ty
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nasa_user -d nasa_tempo_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build: .
    command: celery -A backend worker --loglevel=info --concurrency=2
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgresql://nasa_user:T3mp0@!2025_N4S4_A1rQu4l1ty@db:5432/nasa_tempo_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SECRET_KEY=vl*!l+17p8xg@^s8kd0cq5ug2ogylivy#93k=gi^#aw1p^_ys1
    depends_on:
      - redis
      - db
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A backend beat --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgresql://nasa_user:T3mp0@!2025_N4S4_A1rQu4l1ty@db:5432/nasa_tempo_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SECRET_KEY=vl*!l+17p8xg@^s8kd0cq5ug2ogylivy#93k=gi^#aw1p^_ys1
    depends_on:
      - redis
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: