

services:
  # ===== BACKEND DJANGO =====
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tempo_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgresql://nasa_user:T3mp0@!2025_N4S4_A1rQu4l1ty@db:5432/nasa_tempo_db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ===== BASE DE DONNÉES POSTGRES =====
  db:
    image: postgis/postgis:16-3.4
    container_name: tempo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nasa_tempo_db
      - POSTGRES_USER=nasa_user
      - POSTGRES_PASSWORD=T3mp0@!2025_N4S4_A1rQu4l1ty
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nasa_user -d nasa_tempo_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ===== REDIS =====
  redis:
    image: redis:7-alpine
    container_name: tempo_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== CELERY WORKER =====
  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tempo_celery
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgresql://nasa_user:T3mp0@!2025_N4S4_A1rQu4l1ty@db:5432/nasa_tempo_db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  # ===== FRONTEND REACT =====
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tempo_frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    depends_on:
      - web
    environment:
      - NODE_ENV=production

volumes:
  postgres_data:
  static_volume:
