version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tempo_web
    command: ["/entrypoint.sh"]
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tempo_worker
    command: celery -A backend worker -l info
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    container_name: tempo_redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:15-alpine
    container_name: tempo_db
    environment:
      POSTGRES_DB: tempo
      POSTGRES_USER: tempo_user
      POSTGRES_PASSWORD: tempo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
