# Generated by Django 5.2.7 on 2025-10-04 13:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AirQualityMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("no2", models.FloatField(blank=True, null=True)),
                ("o3", models.FloatField(blank=True, null=True)),
                ("pm25", models.FloatField(blank=True, null=True)),
                ("aqi", models.FloatField(blank=True, null=True)),
                (
                    "aqi_level",
                    models.IntegerField(
                        choices=[
                            (0, "Bon"),
                            (1, "Modéré"),
                            (2, "Mauvais"),
                            (3, "Très mauvais"),
                            (4, "Dangereux"),
                        ],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TempoSatelliteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("no2", models.FloatField(blank=True, null=True)),
                ("o3", models.FloatField(blank=True, null=True)),
                ("so2", models.FloatField(blank=True, null=True)),
                ("co", models.FloatField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("data_quality", models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_aqi", models.FloatField()),
                ("model_version", models.CharField(max_length=50)),
                ("predicted_for", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="tempo_api.airqualitymeasurement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="airqualitymeasurement",
            name="tempo_data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="measurements",
                to="tempo_api.temposatellitedata",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("alert_threshold", models.FloatField(default=100.0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aqi_value", models.FloatField()),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("moderate", "Modérée"),
                            ("unhealthy", "Mauvaise"),
                            ("hazardous", "Dangereuse"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="tempo_api.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("pressure", models.FloatField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="tempo_api_w_timesta_7114f6_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="airqualitymeasurement",
            name="weather",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="measurements",
                to="tempo_api.weatherdata",
            ),
        ),
    ]
